char *lawyer[] = {"LAWYER", 
"Objection!", 
"My client is innocent!", 
"I rest my case!", 
"Sustained!", 
"You must acquit!", 
"Ladies and Gentlemen of the Jury...", 
"Overruled!", 
"That's conjecture, your honor.", 
"Your honor!", 
"I object!", 
"The prosecution rests.", 
"Where were you on the day in question?", 
"Your honor, I move for a mistrial.", 
"Call your next witness", 
"Burden of proof!", 
"My opponent has no evidence.",
"May the record reflect",
"I move to strike",
"Could we have a sidebar?",
"I have no further questions",
"Remember, you are under oath."};